export const GET_FARMER_LIST = 'GET_FARMER_LIST';
export const GET_FARMER_LIST_SUCCESS = 'GET_FARMER_LIST_SUCCESS';
export const GET_FARMER_LIST_FAILED = 'GET_FARMER_LIST_FAILED';

export const GET_SINGLE_FARMER = 'GET_SINGLE_FARMER';
export const GET_SINGLE_FARMER_SUCCESS = 'GET_SINGLE_FARMER_SUCCESS';
export const GET_SINGLE_FARMER_FAILED = 'GET_SINGLE_FARMER_FAILED';


export const EDIT_FARMER = 'EDIT_FARMER';
export const EDIT_FARMER_SUCCESS = 'EDIT_FARMER_SUCCESS';
export const EDIT_FARMER_FAILED = 'EDIT_FARMER_FAILED';

export const DELETE_FARMER = 'DELETE_FARMER';
export const DELETE_FARMER_SUCCESS = 'DELETE_FARMER_SUCCESS';
export const DELETE_FARMER_FAILED = 'DELETE_FARMER_FAILED';
