export const GET_STATION_LIST = 'GET_STATION_LIST';
export const GET_STATION_LIST_SUCCESS = 'GET_STATION_LIST_SUCCESS';
export const GET_STATION_LIST_FAILED = 'GET_STATION_FAILED';

export const GET_SINGLE_STATION = 'GET_SINGLE_STATION';
export const GET_SINGLE_STATION_SUCCESS = 'GET_SINGLE_STATION_SUCCESS';
export const GET_SINGLE_STATION_FAILED = 'GET_SINGLE_STATION_FAILED';

export const CREATE_STATION = 'CREATE_STATION';
export const CREATE_STATION_SUCCESS = 'CREATE_STATION_SUCCESS';
export const CREATE_STATION_FAILED = 'CREATE_AGENT_FAILED';


export const EDIT_STATION = 'EDIT_STATION';
export const EDIT_STATION_SUCCESS = 'EDIT_STATION_SUCCESS';
export const EDIT_STATION_FAILED = 'EDIT_STATION_FAILED';

export const DELETE_STATION = 'DELETE_STATION';
export const DELETE_STATION_SUCCESS = 'DELETE_STATION_SUCCESS';
export const DELETE_STATION_FAILED = 'DELETE_STATION_FAILED';
