export const GET_AGENT = 'GET_AGENT';
export const GET_AGENT_SUCCESS = 'GET_AGENT_SUCCESS';
export const GET_AGENT_FAILED = 'GET_AGENT_FAILED';

export const GET_SINGLE_AGENT = 'GET_SINGLE_AGENT';
export const GET_SINGLE_AGENT_SUCCESS = 'GET_SINGLE_AGENT_SUCCESS';
export const GET_SINGLE_AGENT_FAILED = 'GET_SINGLE_AGENT_FAILED';

export const CREATE_AGENT = 'CREATE_AGENT';
export const CREATE_AGENT_SUCCESS = 'CREATE_AGENT_SUCCESS';
export const CREATE_AGENT_FAILED = 'CREATE_AGENT_FAILED';


export const EDIT_AGENT = 'EDIT_AGENT';
export const EDIT_AGENT_SUCCESS = 'EDIT_AGENT_SUCCESS';
export const EDIT_AGENT_FAILED = 'EDIT_AGENT_FAILED';

export const DELETE_AGENT = 'DELETE_AGENT';
export const DELETE_AGENT_SUCCESS = 'DELETE_AGENT_SUCCESS';
export const DELETE_AGENT_FAILED = 'DELETE_AGENT_FAILED';
